apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-cluster
  region: ap-northeast-1

fargateProfiles:
  - name: fargate-default
    selectors:
    - namespace: kube-system
    - namespace: default