apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mysql-pass
    literals:
      - password=kvsvk
resources:
  - pvc.yaml
  - service.yaml
  - mysql_wordpress.yaml
  - wordpress.yaml
